version: '3.3'
services:
  database:
    image: sameersbn/postgresql:latest
    container_name: dogbook-db
    environment:
      - DB_NAME=dogbook-db-local,dogbook-db-test
      - PG_TRUST_LOCALNET=true
    ports:
      - '5432:5432'

  redis:
    image: redis
    container_name: dogbook-redis
    ports:
      - '6379:6379'
